added http status codes
vglalitha/maven.demo pull request #3
Opened 2021-10-27 11:27 UTC by vglalitha

2021-10-31 02:14 UTC, SupriyaPamulapati approved these changes

2021-11-02 04:38 UTC, PoojaMohite-Khoros requested changes

2021-11-02 04:38 UTC, PoojaMohite-Khoros commented on dropwizard-demo/src/main/java/com/dep/config/BRSConfiguration.java
> +public class BRSConfiguration extends Configuration {
Address this please

2021-11-02 04:38 UTC, PoojaMohite-Khoros commented on dropwizard-demo/src/main/java/com/dep/resource/DropResource.java
> +                return Response.status(500, "request incomplete").build();
U want to send incomplete request after successful post ???

2021-11-02 04:38 UTC, PoojaMohite-Khoros commented on dropwizard-demo/src/main/java/com/dep/resource/DropResource.java
> +                return Response.status(200,"successfully tweeted").build();
Dont u think this return statement should be for successful tweet 
And what u r returning for success tweet to be here at catch ???

2021-11-02 04:38 UTC, PoojaMohite-Khoros commented on dropwizard-demo/src/main/java/com/dep/resource/DropResource.java
> +        String str[] = new String[size];
Use a List instead of String Array
https://www.geeksforgeeks.org/list-interface-java-examples/
Please refer above link for examples

2021-11-02 05:21 UTC, vglalitha commented on dropwizard-demo/src/main/java/com/dep/config/BRSConfiguration.java
> +public class BRSConfiguration extends Configuration {
Sorry ,previously this file is used for healthcheck purpose ,now its not needed.

2021-11-02 09:01 UTC, PoojaMohite-Khoros approved these changes
Please minor address reviews and Merge the PR

2021-11-02 09:01 UTC, PoojaMohite-Khoros commented on pom.xml
Delete one of the pom file

2021-11-02 10:04 UTC, merged